---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)

data(ny_noaa)

ny_noaa |> 
  group_by(id) |> 
  summarize(n_obs=n())
ny_noaa =
  ny_noaa |> 
  filter(
    between(date, as.Date('1982-01-01'), as.Date('1983-12-31')),
    id %in% c("USW00094728", "USC00300023", "USC00303033", "USC00306314")) |> 
  mutate(
    name = recode(
      id, 
      USW00094728 = "Central_Park", 
      USC00300023 = "Addison",
      USC00303033 = "Fredonia",
      USC00306314 = "Oswego_East"),
    tmin = as.numeric(tmin)/10,
    tmax = as.numeric(tmax)/10) |>
  select(name, id, everything())
```

**NOTE**: Weather data was pulled from the NOAA National Climatic Data Center.

Column {data-width=650}
-----------------------------------------------------------------------

### Average Temperature 1982- 1983

```{r}
ny_noaa |> 
  mutate(avg_temp= (tmin+tmax)/2) |> 
  plot_ly(x=~date, y=~avg_temp, color=~name, type= 'scatter', mode= 'lines')
```

Column {data-width=350}
-----------------------------------------------------------------------

### Dry vs. Light Rain vs. Rainy Days: 1982-1983

```{r}
ny_noaa |> 
  mutate(precip_category = ifelse(prcp < 1, 1, ifelse(prcp >= 1 & prcp <= 100, 2, 3)),
         precip_category = recode(precip_category,
    "1" = "dry",
    "2" = "light rain",
    "3" = "rainy"
  ))|> 
  group_by(precip_category, name) |> 
  summarize(n_obs=n()) |> 
  plot_ly(
    x=~precip_category, y=~n_obs, color=~name, type="bar", colors="viridis")
```

### Box Plot of Avg Temperature

```{r}
ny_noaa |> 
  mutate(avg_temp= (tmin+tmax/2)) |> 
  plot_ly(y =~avg_temp, color = ~name, type = "box", colors = "viridis")
```

