---
title: "HW4 Dashboard"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

Focus on the Instacart data.

```{r}
data("instacart")

insta_df= 
  instacart |> 
  as_tibble() |> 
  sample_n(10000)

insta_df |> 
  group_by(department) |> 
  summarize(n_obs=n()) |> 
  filter(n_obs >400) |> 
  arrange(n_obs)

```

Scaterrplot!

```{r}
insta_df |> 
  group_by(department) |> 
  summarize(n_obs=n()) |> 
  filter(n_obs >400) |> 
  arrange(n_obs)
  mutate(text_label= str_c("Price: $", price, "\nRating: ", stars)) |>
 plot_ly(
    x = ~department, y = ~long, color= ~price, text=~text_label,
    type= "scatter", mode= "markers", alpha= 0.5)
```
`str_c` = string combine
`str_c("Label for variable", variable name, "Label for variable", variable name))
\n = new line

Let's do BOX PLOT


BAR PLOT
```{r}
insta_df |> 
  count(department) |> 
  mutate(department= fct_reorder(department, n)) |> 
  plot_ly(
    x = ~department, y= ~n, color= ~department, type= "bar", colors= "viridis")
```

```